version: '3'

services:

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "80:8000"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
